# Generated by Django 3.2.18 on 2023-05-01 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diseasegroup',
            options={'verbose_name': 'Группа заболеваний', 'verbose_name_plural': 'Группы заболеваний'},
        ),
    ]
