# Generated by Django 3.2.18 on 2023-04-25 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventstatistic',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stats.diseasegroup', verbose_name='Группа заболевания'),
            preserve_default=False,
        ),
    ]
