# Generated by Django 3.2.18 on 2023-04-05 10:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import stats.models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_deathstatistic_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deathstatistic',
            name='unique',
        ),
        migrations.AddField(
            model_name='preventstatistic',
            name='curable',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preventstatistic',
            name='disease',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preventstatistic',
            name='gender',
            field=models.CharField(choices=[('муж', 'муж'), ('жен', 'жен'), ('всего', 'всего')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preventstatistic',
            name='preventable',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preventstatistic',
            name='preventive',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preventstatistic',
            name='region',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='stats.region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preventstatistic',
            name='standard',
            field=models.CharField(choices=[('ОЭСР', 'ОЭСР'), ('по РК', 'по РК')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preventstatistic',
            name='year',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(2015), stats.models.max_value_current_year]),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='deathstatistic',
            constraint=models.UniqueConstraint(fields=('region', 'year', 'age', 'gender', 'disease_name'), name='death_statistic_unique'),
        ),
        migrations.AddConstraint(
            model_name='preventstatistic',
            constraint=models.UniqueConstraint(fields=('region', 'year', 'disease', 'standard', 'gender'), name='prevent_statistic_unique'),
        ),
    ]
